// 国家代码映射表
export const COUNTRY_CODES: Record<string, string> = {
  'US': '美国',
  'CN': '中国',
  'JP': '日本',
  'GB': '英国',
  'DE': '德国',
  'FR': '法国',
  'BR': '巴西',
  'IN': '印度',
  'CA': '加拿大',
  'AU': '澳大利亚',
  'KR': '韩国',
  'RU': '俄罗斯',
  'IT': '意大利',
  'ES': '西班牙',
  'MX': '墨西哥',
  'NL': '荷兰',
  'SE': '瑞典',
  'CH': '瑞士',
  'PL': '波兰',
  'BE': '比利时',
  'AR': '阿根廷',
  'NO': '挪威',
  'TW': '台湾',
  'SG': '新加坡',
  'HK': '香港',
  'TH': '泰国',
  'MY': '马来西亚',
  'ID': '印度尼西亚',
  'PH': '菲律宾',
  'VN': '越南',
  'TR': '土耳其',
  'SA': '沙特阿拉伯',
  'AE': '阿联酋',
  'EG': '埃及',
  'ZA': '南非',
  'IL': '以色列',
  'CL': '智利',
  'CO': '哥伦比亚',
  'PE': '秘鲁',
  'VE': '委内瑞拉',
  'NZ': '新西兰',
  'IE': '爱尔兰',
  'DK': '丹麦',
  'FI': '芬兰',
  'PT': '葡萄牙',
  'CZ': '捷克',
  'AT': '奥地利',
  'GR': '希腊',
  'UA': '乌克兰',
  'RO': '罗马尼亚',
  'HU': '匈牙利',
  'PK': '巴基斯坦'
}

export function getCountryName(code: string): string {
  return COUNTRY_CODES[code] || code
}